### PR TITLE
Push sarthi image on release to GH packages

### PR DESCRIPTION
**Pull request by Srijan-SS02**
#27 
@tushar5526  please let me know if this is in the right direction or you need any changes

### CODE REVIEW

**Comment by Srijan-SS02** [comment]
Screenshot from 2024-05-23 22-23-46

**Review by Mr-Sunglasses — APPROVED** [review]
ḺGTM 👍🏻 , thanks @Srijan-SS02

**Comment by Mr-Sunglasses** [comment]
@Srijan-SS02, Please run `pre-commit` to `release.yml` so that the tests for pre-commit can pass.

**Review by Mr-Sunglasses — APPROVED** [review]
Thanks 👍

**Pull request merged**
